-- 1. Create Groups Table
CREATE TABLE groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  default_toll DECIMAL DEFAULT 80,
  default_deposit DECIMAL DEFAULT 300,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Members Table
CREATE TABLE members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT REFERENCES groups(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  phone TEXT,
  balance DECIMAL DEFAULT 0,
  avatar_color TEXT DEFAULT '#10b981',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Trips Table
CREATE TABLE trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT REFERENCES groups(id) ON DELETE CASCADE,
  trip_date DATE DEFAULT CURRENT_DATE,
  total_toll DECIMAL NOT NULL,
  traveler_count INTEGER NOT NULL,
  per_person_cost DECIMAL NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Trip Members (Many-to-Many)
CREATE TABLE trip_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id BIGINT REFERENCES trips(id) ON DELETE CASCADE,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  cost_share DECIMAL NOT NULL
);

-- 5. Create Transactions Table
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT REFERENCES groups(id) ON DELETE CASCADE,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- 'deposit' or 'trip'
  amount DECIMAL NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Real-time for all tables
ALTER PUBLICATION supabase_realtime ADD TABLE groups;
ALTER PUBLICATION supabase_realtime ADD TABLE members;
ALTER PUBLICATION supabase_realtime ADD TABLE trips;
ALTER PUBLICATION supabase_realtime ADD TABLE transactions;

-- 6. Create Notifications Table
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER PUBLICATION supabase_realtime ADD TABLE notifications;

-- Insert a default group to start
INSERT INTO groups (name, description) VALUES ('Default Group', 'Main group for toll splitting');
